spring.application.name=diet

# ログ関連
logging.config=classpath:log4j2-spring.xml
logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.example=DEBUG
app.log.path=logs
app.log.name=application.log

# DB
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.batch.jdbc.initialize-schema=always
