spring.application.name=diet

logging.config=classpath:log4j2-spring.xml
logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.example=DEBUG
app.log.path=/opt/tomcat/logs
app.log.name=application.log